name: UI-Test

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nerdbank.GitVersioning needs a full clone
          fetch-depth: 0
      - name: Setup Divvun CI
        uses: divvun/actions/setup@master
        with:
          key: ${{ secrets.DIVVUN_KEY }}
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: '5.x'
      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@master
        with:
          setCommonVars: true
      - name: Get version
        id: version
        uses: divvun/actions/version@master
        with:
          csharp: true
          stable-channel: beta
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install build dependencies
        uses: divvun/actions/pahkat/init@master
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: pahkat-uploader, pahkat-windows-cli, libpahkat_rpc
      - name: Move libpahkat_rpc to appropriate place
        run: |
          cp $env:RUNNER_TEMP\pahkat-prefix\pkg\libpahkat_rpc\bin\pahkat_rpc.dll $env:RUNNER_WORKSPACE\divvun-manager-windows\Divvun.Installer\
          cp $env:RUNNER_TEMP\pahkat-prefix\pkg\libpahkat_rpc\bin\pahkat_rpc.dll $env:RUNNER_WORKSPACE\divvun-manager-windows\Divvun.Installer.OneClick\Costura32\
      - name: Acquire Pahkat Service installer (nightly)
        if: ${{ steps.version.outputs.channel == 'nightly' }}
        run: |
          mkdir ./pahkat-config
          echo "[""https://pahkat.uit.no/divvun-installer/""]`nchannel = ""nightly""" > ./pahkat-config/repos.toml
          pahkat-windows download https://pahkat.uit.no/divvun-installer/packages/pahkat-service --output ./pahkat-service -c ./pahkat-config
          mv ./pahkat-service/* ./pahkat-service-setup.exe
      - name: Acquire Pahkat Service installer (stable)
        if: ${{ steps.version.outputs.channel != 'nightly' }}
        run: |
          mkdir ./pahkat-config
          echo "[""https://pahkat.uit.no/divvun-installer/""]`nchannel = ""beta""" > ./pahkat-config/repos.toml
          pahkat-windows download https://pahkat.uit.no/divvun-installer/packages/pahkat-service --output ./pahkat-service -c ./pahkat-config
          mv ./pahkat-service/* ./pahkat-service-setup.exe
      - name: Install Pahkat Service installer
        run: |
          ./pahkat-service-setup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
      - name: Install WinAppDriver
        run: choco install winappdriver
      - name: Start WinAppDriver
        run: |
          pushd "C:\Program Files (x86)\Windows Application Driver"
          start WinAppDriver.exe
          popd
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nuget restore "Divvun.Installer.sln"
          MSBuild.exe "Divvun.Installer.sln" /p:Configuration=Release /p:Platform=x86 /m  || exit /b !ERRORLEVEL!
      - name: Move Divvun Installer
        run: |
          mkdir "C:\DivvunManager"
          mv Divvun.Installer/bin/x86/Release/* C:\DivvunManager
          dir "C:\DivvunManager"
      - name: Run UI test
        run: |
          dotnet test DivvunUITests
      - name: Grab diagnostic screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            C:\DivvunManager\Screenshots\*