name: UI-Test

on:
  push:
    branches:
      - feature/ui-tests

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nerdbank.GitVersioning needs a full clone
          fetch-depth: 0
      - name: Setup Divvun CI
        uses: divvun/actions/setup@divvun-installer
        with:
          key: ${{ secrets.DIVVUN_KEY }}
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: '5.x'
      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@master
        with:
          setCommonVars: true
      - name: Get version
        id: version
        uses: divvun/actions/version@develop
        with:
          csharp: true
          nightly: master, develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install build dependencies
        uses: divvun/actions/pahkat/init@develop
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: pahkat-uploader, pahkat-windows-cli, libpahkat_rpc
      - name: Move libpahkat_rpc to appropriate place
        run: |
          cp $env:RUNNER_WORKSPACE\pahkat-prefix\pkg\libpahkat_rpc\bin\pahkat_rpc.dll $env:RUNNER_WORKSPACE\divvun-installer-windows\Divvun.Installer\
      - name: Acquire Pahkat Service installer
        run: |
          mkdir ./pahkat-config
          echo "[""https://pahkat.uit.no/divvun-installer/""]`nchannel = ""nightly""" > ./pahkat-config/repos.toml
          pahkat-windows download https://pahkat.uit.no/divvun-installer/packages/pahkat-service --output ./pahkat-service -c ./pahkat-config
          mv ./pahkat-service/* ./pahkat-service-setup.exe
      - name: Install Pahkat Service installer
        run: |
          ./pahkat-service-setup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nuget restore "Divvun.Installer.sln"
          MSBuild.exe "Divvun.Installer.sln" /p:Configuration=Release /p:Platform=x86 /m  || exit /b !ERRORLEVEL!
      - name: Sign code (Divvun Installer exe)
        uses: divvun/actions/codesign@develop
        with:
          path: Divvun.Installer/bin/x86/Release/DivvunInstaller.exe
      - name: Sign code (Pahkat SDK DLL)
        uses: divvun/actions/codesign@develop
        with:
          path: Divvun.Installer/bin/x86/Release/Pahkat.Sdk.dll 
      - name: Sign code (Pahkat SDK RPC DLL)
        uses: divvun/actions/codesign@develop
        with:
          path: Divvun.Installer/bin/x86/Release/Pahkat.Sdk.Rpc.dll 
      - name: Sign code (pahkat_rpc DLL)
        uses: divvun/actions/codesign@develop
        with:
          path: Divvun.Installer/bin/x86/Release/pahkat_rpc.dll
      - name: Create installer
        id: installer
        uses: divvun/actions/inno-setup@develop
        with:
          path: setup.iss
          defines: Version=${{ steps.version.outputs.version }}